// <auto-generated />
using System;
using DevicesApi.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DevicesApi.WebApi.Migrations
{
    [DbContext(typeof(DeviceDbContext))]
    [Migration("20251124000336_FirstMigration")]
    partial class FirstMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.0");

            modelBuilder.Entity("DevicesApi.Domain.Device", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Brand")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasMaxLength(9)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Devices");

                    b.HasData(
                        new
                        {
                            Id = "2fcaefb2-abe6-4a70-b327-bb34f58a66de",
                            Brand = "brand 1",
                            CreatedAt = new DateTimeOffset(new DateTime(2025, 11, 23, 21, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Name = "name 1",
                            State = "Available"
                        },
                        new
                        {
                            Id = "1c39ef8c-f794-481e-8ca9-4ec9a15d0029",
                            Brand = "brand 2",
                            CreatedAt = new DateTimeOffset(new DateTime(2025, 11, 23, 21, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Name = "name 2",
                            State = "InUse"
                        },
                        new
                        {
                            Id = "1dc798b8-febc-4256-b711-3b146203398a",
                            Brand = "brand 3",
                            CreatedAt = new DateTimeOffset(new DateTime(2025, 11, 23, 21, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Name = "name 3",
                            State = "Inactive"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
